# Generated by Django 2.2.5 on 2019-11-27 07:01

import diaries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_auto_20191127_1455'),
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='diaries', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, upload_to=diaries.models.user_path),
        ),
    ]
