# Generated by Django 2.2.5 on 2019-11-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_auto_20191127_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='owner',
            new_name='user',
        ),
    ]
