# Generated by Django 2.2.5 on 2019-11-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191125_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='img_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cast',
            name='cast_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='director',
            name='img_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='director',
            name='name_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='movie',
            name='audience',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='nation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='open_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rank',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
