# Generated by Django 2.2.5 on 2019-11-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191125_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='naver_poster_url',
            field=models.TextField(blank=True),
        ),
    ]
