# Generated by Django 2.2.5 on 2019-11-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20191125_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genreType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
