# Generated by Django 2.2.5 on 2019-11-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20191125_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genreType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='movies.Genre'),
        ),
    ]
