# Generated by Django 2.2.5 on 2019-11-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='naver_link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
