# Generated by Django 2.2.5 on 2019-11-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20191126_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='naver_big_poster_url',
            field=models.TextField(blank=True),
        ),
    ]
