# Generated by Django 2.2.5 on 2019-11-27 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='liked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
