# Generated by Django 2.2.5 on 2019-11-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20191127_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='movies.Movie'),
        ),
    ]
