# Generated by Django 2.2.5 on 2019-11-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20191127_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
