# Generated by Django 2.2.5 on 2019-11-27 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0023_auto_20191127_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='want_users',
            field=models.ManyToManyField(related_name='want_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
